import {AuthProps, withAuth} from '@sentaku/lib'
import {Layout} from '@sentaku/components'
import Head from 'next/head'

export const getServerSideProps = withAuth(async () => {
  return {
    props: {}
  }
})

const Home: React.FC<AuthProps> = (props) => {

  return (
    <Layout title={'Home'} user={props.data?.user}>
      <Head>
        <title>Home</title>
        <link rel="icon" href="/favicon.ico"/>
        <meta name="description" content="Generated by create next app"/>
      </Head>

    </Layout>
  )
}

export default Home
